### ISSUE TITLE
PahoMQTT Client Issue in node.js

### ISSUE THREAD

**Issue by NidhaanTandava** [huangguozhen/paho.mqtt.js#2]
Hi,

While trying to use the module for a nodejs program, I am getting the following error:
var client = new PahoMQTT.client("xxx.yyy.com", 443, "/xyendpoint", "clientId");
             ^

TypeError: PahoMQTT.client is not a function
    at Object.<anonymous> (C:\Workplace\Codes\nodecodes\mqttclient\index.js:2:14)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3

Could you kindly give me guidance on how to resolve this issue.

Thanks & Regards,
Harish

**Comment by NidhaanTandava** [comment]
A small correction:
var client = new PahoMQTT.Client("xxx.yyy.com",** 443, "/xyendpoint", "clientId");
^
'C' is capital
